// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IoTProjectListerExpansion allows custom methods to be added to
// IoTProjectLister.
type IoTProjectListerExpansion interface{}

// IoTProjectNamespaceListerExpansion allows custom methods to be added to
// IoTProjectNamespaceLister.
type IoTProjectNamespaceListerExpansion interface{}
