apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotprojects.hono.eclipse.org
spec:
  group: hono.eclipse.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: iotprojects
    singular: iotproject
    kind: IoTProject
  validation:
    openAPIV3Schema:
      required: ["spec"]
